//go:build fts5

// Package distill handles calling an external LLM API to generate wiki
// source-notes from raw documents.
package distill

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/pieteams/piekbs/internal/kb"
	"github.com/pieteams/piekbs/internal/llmurl"
	"github.com/pieteams/piekbs/internal/synthesize"
)

// Config holds the LLM API configuration.
type Config struct {
	BaseURL string
	Token   string
	Model   string
	APIType string // "openai" (default) or "anthropic"
}

func (c Config) isAnthropic() bool {
	return strings.EqualFold(c.APIType, "anthropic")
}

// IsConfigured returns true when all three fields are non-empty.
func (c Config) IsConfigured() bool {
	return c.BaseURL != "" && c.Token != "" && c.Model != ""
}

// stripConvertedPrefix removes a leading "converted/" path segment so that
// raw/converted/foo/bar.md maps to wiki/source-notes/foo/bar.md.
func stripConvertedPrefix(rel string) string {
	const prefix = "converted" + string(filepath.Separator)
	if strings.HasPrefix(rel, prefix) {
		return rel[len(prefix):]
	}
	return rel
}

// StripCodeFences removes a leading ```[language] ... ``` wrapper if present.
func StripCodeFences(text string) string {
	text = strings.TrimSpace(text)

	// Find opening fence line
	firstNL := strings.IndexByte(text, '\n')
	if firstNL < 0 {
		return text
	}
	firstLine := text[:firstNL]
	if !strings.HasPrefix(firstLine, "```") {
		return text
	}

	// Must end with closing fence
	if !strings.HasSuffix(text, "```") {
		return text
	}

	// Strip first line and last fence line
	inner := text[firstNL+1 : len(text)-3]
	return strings.TrimRight(inner, "\n")
}

// titleRe extracts the title value from a frontmatter `title:` line,
// tolerating optional surrounding quotes.
var titleRe = regexp.MustCompile(`(?m)^title:\s*"?([^"\n]*)"?\s*$`)

// titleFromNote returns the frontmatter title, or fallback if none is found.
func titleFromNote(note, fallback string) string {
	if m := titleRe.FindStringSubmatch(note); m != nil {
		if t := strings.TrimSpace(m[1]); t != "" {
			return t
		}
	}
	return fallback
}

// appendLog appends a greppable, chronological entry to wiki/log.md following
// the OKF/Karpathy convention: `## [YYYY-MM-DD] ingest | <title>`. The file is
// created if absent. Failures are non-fatal and returned for logging.
func appendLog(kbRoot, title string) error {
	logPath := filepath.Join(kbRoot, "wiki", "log.md")
	if err := os.MkdirAll(filepath.Dir(logPath), 0o755); err != nil {
		return err
	}
	entry := fmt.Sprintf("## [%s] ingest | %s\n", time.Now().Format("2006-01-02"), title)
	f, err := os.OpenFile(logPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = f.WriteString(entry)
	return err
}

// SetSourceField rewrites the `sources` field inside the leading YAML
// frontmatter to point at rawRel (a KB-root-relative path like "raw/foo.md").
// It removes any sources entry the LLM produced — inline (`sources: [...]`) or
// block list (`sources:\n  - ...`) — and inserts a canonical block form so the
// wiki↔raw graph link (parsed as a `cites` relation) is always correct.
// If no frontmatter is found, the text is returned unchanged.
func SetSourceField(text, rawRel string) string {
	if !strings.HasPrefix(text, "---\n") {
		return text
	}
	end := strings.Index(text[4:], "\n---")
	if end < 0 {
		return text
	}
	fmStart := 4
	fmEnd := 4 + end // index of the '\n' before closing '---'
	fm := text[fmStart:fmEnd]
	rest := text[fmEnd:]

	var out []string
	skippingList := false
	for _, line := range strings.Split(fm, "\n") {
		trimmed := strings.TrimSpace(line)
		// Drop list items belonging to a sources: block we're removing.
		if skippingList {
			if strings.HasPrefix(trimmed, "- ") || trimmed == "-" {
				continue
			}
			skippingList = false
		}
		if val, ok := strings.CutPrefix(trimmed, "sources:"); ok {
			// Inline form (sources: [..]) → just drop the line.
			// Block form (sources:) with no value → drop following list items too.
			if strings.TrimSpace(val) == "" {
				skippingList = true
			}
			continue
		}
		out = append(out, line)
	}

	newFM := strings.Join(out, "\n")
	newFM = strings.TrimRight(newFM, "\n")
	return "---\n" + newFM + "\nsources:\n  - " + rawRel + rest
}

// GroundProvenance removes unsupported provenance generated by the LLM.
// Source URL, author, and publication date are only retained when backed by
// raw input. Imported is set deterministically from the raw file timestamp.
func GroundProvenance(text, rawContent string, imported time.Time) string {
	rawMeta := parseRawFrontmatter(rawContent)
	resource := rawMeta["source_url"]

	lines := strings.Split(text, "\n")
	inSource := false
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)

		if strings.HasPrefix(trimmed, "resource:") {
			generated := yamlScalar(strings.TrimSpace(strings.TrimPrefix(trimmed, "resource:")))
			switch {
			case resource != "":
				lines[i] = "resource: " + strconv.Quote(resource)
			case generated != "" && strings.Contains(rawContent, generated):
				// Keep explicitly sourced citations.
			default:
				lines[i] = "resource: \"\""
			}
			continue
		}

		if trimmed == "## Source" {
			inSource = true
			continue
		}
		if inSource && strings.HasPrefix(trimmed, "## ") {
			inSource = false
		}
		if !inSource {
			continue
		}

		key, value, ok := sourceField(line)
		if !ok {
			continue
		}
		switch key {
		case "author":
			if explicit := rawMeta["author"]; explicit != "" {
				lines[i] = "- Author: " + explicit
			} else if value == "" || !strings.Contains(rawContent, value) {
				lines[i] = "- Author: Not provided in source."
			}
		case "published":
			explicit := rawMeta["published"]
			if explicit == "" {
				explicit = rawMeta["timestamp"]
			}
			if explicit != "" {
				lines[i] = "- Published: " + explicit
			} else if value == "" || !strings.Contains(rawContent, value) {
				lines[i] = "- Published: Not provided in source."
			}
		case "imported":
			lines[i] = "- Imported: " + imported.UTC().Format("2006-01-02")
		}
	}
	return strings.Join(lines, "\n")
}

func parseRawFrontmatter(raw string) map[string]string {
	values := map[string]string{}
	if !strings.HasPrefix(raw, "---\n") {
		return values
	}
	end := strings.Index(raw[4:], "\n---")
	if end < 0 {
		return values
	}
	for _, line := range strings.Split(raw[4:4+end], "\n") {
		key, value, ok := strings.Cut(line, ":")
		if !ok {
			continue
		}
		key = strings.TrimSpace(strings.ToLower(key))
		switch key {
		case "source_url", "author", "published", "timestamp":
			values[key] = yamlScalar(strings.TrimSpace(value))
		}
	}
	return values
}

func yamlScalar(value string) string {
	value = strings.TrimSpace(value)
	if len(value) >= 2 && ((value[0] == '"' && value[len(value)-1] == '"') ||
		(value[0] == '\'' && value[len(value)-1] == '\'')) {
		if value[0] == '"' {
			if unquoted, err := strconv.Unquote(value); err == nil {
				return unquoted
			}
		}
		return value[1 : len(value)-1]
	}
	return value
}

func sourceField(line string) (key, value string, ok bool) {
	trimmed := strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(line), "-"))
	trimmed = strings.ReplaceAll(trimmed, "**", "")
	name, value, ok := strings.Cut(trimmed, ":")
	if !ok {
		return "", "", false
	}
	key = strings.ToLower(strings.TrimSpace(name))
	switch key {
	case "author", "published", "imported":
		return key, strings.TrimSpace(value), true
	default:
		return "", "", false
	}
}

// FindNewFiles walks kbRoot/raw/ for .md files that do not yet have a
// corresponding source-note under kbRoot/wiki/source-notes/.
// index.md and log.md are skipped.
func FindNewFiles(kbRoot string) []string {
	rawDir := filepath.Join(kbRoot, "raw")
	notesDir := filepath.Join(kbRoot, "wiki", "source-notes")

	var result []string
	_ = filepath.Walk(rawDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		if filepath.Ext(path) != ".md" {
			return nil
		}

		base := filepath.Base(path)
		if base == "index.md" || base == "log.md" {
			return nil
		}

		// Build relative path from rawDir, stripping converted/ prefix so that
		// raw/converted/foo/bar.md maps to wiki/source-notes/foo/bar.md.
		rel, err := filepath.Rel(rawDir, path)
		if err != nil {
			return nil
		}
		rel = stripConvertedPrefix(rel)

		notePath := filepath.Join(notesDir, rel)
		if _, err := os.Stat(notePath); os.IsNotExist(err) {
			result = append(result, path)
		}
		return nil
	})
	return result
}

// anthropicRequest is the JSON body sent to the Anthropic messages endpoint.
type anthropicRequest struct {
	Model     string             `json:"model"`
	MaxTokens int                `json:"max_tokens"`
	System    string             `json:"system"`
	Messages  []anthropicMessage `json:"messages"`
}

type anthropicMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

// anthropicResponse is the subset of the Anthropic messages response we care about.
type anthropicResponse struct {
	Content []struct {
		Type string `json:"type"`
		Text string `json:"text"`
	} `json:"content"`
}

// CallLLM sends rawContent to the configured LLM and returns the generated text.
// kbRoot is used to load a custom system prompt from schema/templates/source-note.md
// if present; otherwise the built-in default prompt is used.
// relatedContext, if non-empty, is appended to the system prompt to inject
// related-page context discovered via vector search.
// api_type in config selects the wire format: "anthropic" or "openai" (default).
func CallLLM(config Config, kbRoot, rawContent, relatedContext string) (string, error) {
	system := buildSystemPrompt(kbRoot)
	if relatedContext != "" {
		system = system + relatedContext
	}
	if config.isAnthropic() {
		return callAnthropic(config, system, rawContent)
	}
	return callOpenAI(config, system, rawContent)
}

// callAnthropic uses the Anthropic Messages API format.
func callAnthropic(config Config, system, userContent string) (string, error) {
	reqBody := anthropicRequest{
		Model:     config.Model,
		MaxTokens: 8192,
		System:    system,
		Messages:  []anthropicMessage{{Role: "user", Content: userContent}},
	}
	bodyBytes, err := json.Marshal(reqBody)
	if err != nil {
		return "", fmt.Errorf("marshal request: %w", err)
	}

	url := llmurl.Endpoint(config.BaseURL, "/v1/messages")
	req, err := http.NewRequest(http.MethodPost, url, bytes.NewReader(bodyBytes))
	if err != nil {
		return "", fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-api-key", config.Token)
	req.Header.Set("anthropic-version", "2023-06-01")

	respBody, err := doHTTP(req)
	if err != nil {
		return "", err
	}

	var apiResp anthropicResponse
	if err := json.Unmarshal(respBody, &apiResp); err != nil {
		return "", fmt.Errorf("decode response: %w", err)
	}
	var parts []string
	for _, block := range apiResp.Content {
		if block.Type == "text" {
			parts = append(parts, block.Text)
		}
	}
	if len(parts) == 0 {
		return "", fmt.Errorf("LLM returned no text content")
	}
	return strings.Join(parts, ""), nil
}

// callOpenAI uses the OpenAI Chat Completions API format (compatible with most providers).
func callOpenAI(config Config, system, userContent string) (string, error) {
	type message struct {
		Role    string `json:"role"`
		Content string `json:"content"`
	}
	type request struct {
		Model     string    `json:"model"`
		MaxTokens int       `json:"max_tokens"`
		Messages  []message `json:"messages"`
	}
	type choice struct {
		Message message `json:"message"`
	}
	type response struct {
		Choices []choice `json:"choices"`
	}

	reqBody, err := json.Marshal(request{
		Model:     config.Model,
		MaxTokens: 8192,
		Messages: []message{
			{Role: "system", Content: system},
			{Role: "user", Content: userContent},
		},
	})
	if err != nil {
		return "", fmt.Errorf("marshal request: %w", err)
	}

	url := llmurl.Endpoint(config.BaseURL, "/v1/chat/completions")
	req, err := http.NewRequest(http.MethodPost, url, bytes.NewReader(reqBody))
	if err != nil {
		return "", fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+config.Token)

	respBody, err := doHTTP(req)
	if err != nil {
		return "", err
	}

	var apiResp response
	if err := json.Unmarshal(respBody, &apiResp); err != nil {
		return "", fmt.Errorf("decode response: %w", err)
	}
	if len(apiResp.Choices) == 0 {
		return "", fmt.Errorf("LLM returned no choices")
	}
	return apiResp.Choices[0].Message.Content, nil
}

// doHTTP executes the request with a 120s timeout and returns the response body.
func doHTTP(req *http.Request) ([]byte, error) {
	client := &http.Client{Timeout: 120 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("http request: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("LLM API returned %d: %s", resp.StatusCode, body)
	}
	return body, nil
}

// isTechnicalCatalog detects documents that are too technical/dense for LLM
// distillation — they contain large numbered entity lists (e.g. M01-M43) or
// many database table identifiers. These should be lightly processed to
// preserve all precise identifiers for FTS search.
func isTechnicalCatalog(content string) bool {
	lines := strings.Split(content, "\n")
	if len(lines) < 50 {
		return false
	}
	// Count numbered entity patterns: M01, M02... or similar coded lists
	numberedRe := regexp.MustCompile(`\bM\d{2}\b`)
	tableRe := regexp.MustCompile(`(?i)(iceberg_|dim_|dwd_|hive_|matrixdb|\.im_edge\.)`)
	numberedCount := 0
	tableCount := 0
	tableLineCount := 0
	for _, line := range lines {
		if numberedRe.MatchString(line) {
			numberedCount++
		}
		if tableRe.MatchString(line) {
			tableCount++
		}
		if strings.HasPrefix(strings.TrimSpace(line), "|") {
			tableLineCount++
		}
	}
	// High table density (>30% of lines are table rows) indicates a data dictionary
	// or field catalog that should be preserved verbatim rather than summarized.
	tableRatio := float64(tableLineCount) / float64(len(lines))
	return numberedCount >= 5 || tableCount >= 10 || tableRatio >= 0.30
}

// lightweightNote generates a source-note without LLM distillation.
// The full de-noised content is preserved for FTS indexing.
// Only frontmatter metadata is generated from the file name and content.
func lightweightNote(rawPath, rawDocID, content string) string {
	// Extract title from first heading or filename
	title := strings.TrimSuffix(filepath.Base(rawPath), filepath.Ext(rawPath))
	for _, line := range strings.Split(content, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "# ") {
			title = strings.TrimPrefix(line, "# ")
			break
		}
		if strings.HasPrefix(line, "**") && strings.HasSuffix(line, "**") {
			title = strings.Trim(line, "*")
			break
		}
	}

	// Remove base64 image data (large, useless for search)
	imgRe := regexp.MustCompile(`!\[.*?\]\(data:image/[^;]+;base64,[^)]{20,}\)`)
	cleaned := imgRe.ReplaceAllString(content, "<!-- image removed -->")

	// Remove markdown image references with media paths
	mediaRe := regexp.MustCompile(`!\[.*?\]\(media/[^)]+\)`)
	cleaned = mediaRe.ReplaceAllString(cleaned, "")

	now := time.Now().UTC().Format("2006-01-02T15:04:05Z")

	return fmt.Sprintf(`---
type: source-note
title: %q
description: ""
tags: []
resource: ""
sources:
  - %s
timestamp: %q
processing: lightweight
---

%s
`, title, rawDocID, now, strings.TrimSpace(cleaned))
}

// DistillFile reads the raw file at rawPath, calls the LLM with optional
// related-page context from vector search, and writes the source-note.
// For technical catalog documents (large numbered lists, many table names),
// lightweight processing is used instead to preserve all identifiers for FTS.
// embedder may be nil — when nil, vector lookup is skipped.
func DistillFile(config Config, rawPath, kbRoot string, embedder kb.Embedder) error {
	rawContent, err := os.ReadFile(rawPath)
	if err != nil {
		return fmt.Errorf("read raw file: %w", err)
	}

	var generated string

	if isTechnicalCatalog(string(rawContent)) {
		// Lightweight path: preserve full content for FTS, skip LLM
		rawDir := filepath.Join(kbRoot, "raw")
		rel, err := filepath.Rel(rawDir, rawPath)
		if err != nil {
			return fmt.Errorf("relative path: %w", err)
		}
		rawDocID := "raw/" + filepath.ToSlash(rel)
		generated = lightweightNote(rawPath, rawDocID, string(rawContent))
		fmt.Printf("  [lightweight] %s\n", filepath.Base(rawPath))
	} else {
		relatedContext := findRelatedNotes()
		generated, err = CallLLM(config, kbRoot, string(rawContent), relatedContext)
		if err != nil {
			return fmt.Errorf("call LLM: %w", err)
		}
		generated = StripCodeFences(generated)
	}

	info, statErr := os.Stat(rawPath)
	imported := time.Now()
	if statErr == nil {
		imported = info.ModTime()
	}
	generated = GroundProvenance(generated, string(rawContent), imported)

	rawDir := filepath.Join(kbRoot, "raw")
	rel, err := filepath.Rel(rawDir, rawPath)
	if err != nil {
		return fmt.Errorf("relative path: %w", err)
	}

	// Force the sources field to the raw source's DocID (KB-root-relative,
	// slash-separated) so index.go links the note to its raw source via `cites`.
	rawDocID := "raw/" + filepath.ToSlash(rel)
	generated = SetSourceField(generated, rawDocID)

	// Strip converted/ prefix: raw/converted/foo/bar.md → source-notes/foo/bar.md
	noteRel := stripConvertedPrefix(rel)
	notePath := filepath.Join(kbRoot, "wiki", "source-notes", noteRel)
	if err := os.MkdirAll(filepath.Dir(notePath), 0o755); err != nil {
		return fmt.Errorf("create notes dir: %w", err)
	}

	if err := os.WriteFile(notePath, []byte(generated), 0o644); err != nil {
		return fmt.Errorf("write note: %w", err)
	}

	// Record a chronological ingest entry in wiki/log.md.
	stem := strings.TrimSuffix(filepath.Base(rel), filepath.Ext(rel))
	if err := appendLog(kbRoot, titleFromNote(generated, stem)); err != nil {
		return fmt.Errorf("append log: %w", err)
	}

	// Trigger incremental synthesize for the newly created source-note.
	// Best-effort: errors are logged but not returned to the caller.
	synthCfg := synthesize.Config{
		BaseURL: config.BaseURL,
		Token:   config.Token,
		Model:   config.Model,
		APIType: config.APIType,
	}
	noteRelPath := "wiki/source-notes/" + filepath.ToSlash(noteRel)
	if err := synthesize.RunIncremental(synthCfg, kbRoot, noteRelPath); err != nil {
		fmt.Printf("distill: incremental synthesize: %v\n", err)
	}
	return nil
}

// Run finds all undistilled raw files and distills each one.
// Returns (count, nil) on success or (0, err) on the first failure.
func Run(kbRoot string, config Config) (int, error) {
	if !config.IsConfigured() {
		return 0, fmt.Errorf("LLM config incomplete: BaseURL, Token, and Model are all required")
	}

	files := FindNewFiles(kbRoot)
	if len(files) == 0 {
		return 0, nil
	}

	for _, rawPath := range files {
		rel, _ := filepath.Rel(filepath.Join(kbRoot, "raw"), rawPath)
		fmt.Printf("distilling: raw/%s\n", rel)
		if err := DistillFile(config, rawPath, kbRoot, nil); err != nil {
			return 0, fmt.Errorf("distill %s: %w", rawPath, err)
		}
		fmt.Printf("distilled:  raw/%s\n", rel)
	}
	return len(files), nil
}
